# Generated by Django 2.2.6 on 2020-12-02 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
                ('short_name', models.CharField(max_length=50, verbose_name='короткое имя')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name_plural': 'справочники',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10, verbose_name='версия справочника')),
                ('initial_date', models.DateField(verbose_name='дата действия')),
                ('glossary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version', to='main_app.Glossary', verbose_name='справочник')),
            ],
            options={
                'verbose_name_plural': 'Версии',
                'unique_together': {('glossary', 'version')},
            },
        ),
        migrations.CreateModel(
            name='GlossaryElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=50, verbose_name='артикл')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='значение')),
                ('glossary_ver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element', to='main_app.Version', verbose_name='справочник')),
            ],
            options={
                'verbose_name_plural': 'элементы справочника',
            },
        ),
    ]
