# Generated by Django 2.2.6 on 2020-11-30 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('version', models.CharField(max_length=10, unique=True)),
                ('initial_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefBookItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('ref_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='main_app.ReferenceBook')),
            ],
        ),
    ]
